server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
       - id: user-ms
         uri:
          lb://user-ms
         predicates:
         - Path=/api/user/**
       - id: contacts-ms
         uri:
          lb://contacts-ms 
         predicates:
         - Path=/api/contacts/**		 

eureka:
 instance:
  hostname: localhost
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/    
