server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
       - id: UserMicroService
         uri:
          lb://UserMicroService
         predicates:
         - Path=/api/user/**
       - id: ContactsMicroServices 
         uri:
          lb://ContactsMicroServices 
         predicates:
         - Path=/api/contacts/**		 

eureka:
 instance:
  hostname: localhost
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/    
