server:
  port: 8080
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
       - id: user-ms
         uri:
           lb://USER-MS
         predicates:
         - Path=/user/**
       - id: contact-ms
         uri:
          lb://CONTACT-MS
         predicates:
         - Path=/contacts/**		 
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.eureka: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: gateway,health

eureka:
 instance:
  hostname: localhost
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/    
